services:

    # @doctrine.orm.entity_manager

    command.sheet:
        class: Payroll\Command\SheetCommand

    command.start:
        class: Payroll\Command\StartCommand

    command.stop:
        class: Payroll\Command\StopCommand

    command.now:
        class: Payroll\Command\NowCommand

    command.display:
        class: Payroll\Command\DisplayCommand

    command.manual:
        class: Payroll\Command\ManualCommand

    manager.sheet_manager:
        class: Payroll\Manager\SheetManager
        arguments: ['@doctrine.orm.entity_manager']

    manager.item_manager:
        class: Payroll\Manager\ItemManager
        arguments: ['@doctrine.orm.entity_manager']
